apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ##SERVICE_NAME##-autoscaler
  namespace: ##SERVICE_NAMESPACE##
  labels: 
    app: ##SERVICE_NAME##
    environment: ##ENVIRONMENT##
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ##SERVICE_NAME##-deployment
  minReplicas: ##MIN_REPLICAS##
  maxReplicas: ##MAX_REPLICAS##
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: ##CPU_SCALE_THRESHOLD##
  - type: Resource
    resource:
      name: memory
      target: 
        type: AverageValue
        averageValue: ##MEMORY_SCALE_THRESHOLD##